#!/usr/bin/env python

import os

PRIORITY = {
    "Inbox":   0,
    "Starred": 1,
    "Sent":    2,
    "Drafts":  3,
    "Archive": 4,
    "Trash":   5,
    "Spam":    6,
}

EXCLUDE_ACCOUNTS = [
    'Search',   # Here we keep results of search
]

EXCLUDE_MAIL_DIRS = [
    'cur',
    'new',
    'tmp',
]

MAIL_DIR = os.getenv('HOME') + '/.mail'
MUTT_FILE = os.getenv('HOME') + '/.mutt/config/mailboxes.mutt'

def getKey(item):
    curr_value = len(PRIORITY) + 1000
    for key in PRIORITY:
        if item.find(key) > -1:
            curr_value = PRIORITY[key]
            break;
    return curr_value

# Generate accounts exclude hidden directories and directories from EXCLUDE_ACCOUNTS
accounts = [f for f in os.listdir(MAIL_DIR) if os.path.isdir(os.path.join(MAIL_DIR, f)) and f[0] != '.' and f not in EXCLUDE_ACCOUNTS]
mailboxes = []
for acc in accounts:
    mailboxes.append(acc)
    account_dir = os.path.join(MAIL_DIR, acc)
    m = [dp.replace(MAIL_DIR + '/', '') for dp, _, _ in os.walk(account_dir) if dp.split('/')[-1] not in EXCLUDE_MAIL_DIRS and dp.split('/')[-1] != acc]
    m = sorted(m, key=getKey)
    mailboxes.extend(m)

for i in range(len(mailboxes)):
    mailboxes[i] = "\"+" + mailboxes[i] + "\""

with open(MUTT_FILE, 'w') as f:
    f.write("# THIS FILE WAS GENERATED BY $HOME/.mutt/scripts/mailboxes.py\n\n")
    f.write("mailboxes " + ' '.join(mailboxes) + '\n')

